2025-08-15 18:03:28 | ERROR | MainProcess | root | [ERROR] during learn: [WinError 232] The pipe is being closed
Traceback (most recent call last):
  File "D:\bot\train_rl.py", line 264, in train_one_file
    model.learn(total_timesteps=int(args.total_steps), callback=cb, progress_bar=args.progress)
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\ppo\ppo.py", line 311, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 311, in learn
    total_timesteps, callback = self._setup_learn(
                                ^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\base_class.py", line 423, in _setup_learn
    self._last_obs = self.env.reset()  # type: ignore[assignment]
                     ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\vec_env\vec_normalize.py", line 297, in reset
    obs = self.venv.reset()
          ^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 144, in reset
    remote.send(("reset", (self._seeds[env_idx], self._options[env_idx])))
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\multiprocessing\connection.py", line 289, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [WinError 232] The pipe is being closed
2025-08-15 18:33:10 | WARNING | MainProcess | root | [INTERRUPT] KeyboardInterrupt — saving.
2025-08-15 18:52:50 | WARNING | MainProcess | root | [INTERRUPT] KeyboardInterrupt — saving.
2025-08-15 19:02:57 | WARNING | MainProcess | root | [PPO] batch_size (65536) > n_envs*n_steps (4096) — سيتم تقليمه
2025-08-15 21:26:35 | ERROR | MainProcess | root | [ERROR] during learn: 
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\multiprocessing\connection.py", line 328, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bot\Train_RL.py", line 241, in train_one_file
    model.learn(total_timesteps=int(args.total_steps), callback=cb, progress_bar=args.progress)
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\ppo\ppo.py", line 311, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 324, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 218, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py", line 222, in step
    return self.step_wait()
           ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\vec_env\vec_normalize.py", line 181, in step_wait
    obs, rewards, dones, infos = self.venv.step_wait()
                                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 137, in step_wait
    results = [remote.recv() for remote in self.remotes]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 137, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
               ^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\multiprocessing\connection.py", line 337, in _recv_bytes
    raise EOFError
EOFError
2025-08-15 21:38:30 | ERROR | MainProcess | root | [ERROR] during learn: 
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\multiprocessing\connection.py", line 328, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bot\Train_RL.py", line 241, in train_one_file
    model.learn(total_timesteps=int(args.total_steps), callback=cb, progress_bar=args.progress)
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\ppo\ppo.py", line 311, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 324, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 218, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py", line 222, in step
    return self.step_wait()
           ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\vec_env\vec_normalize.py", line 181, in step_wait
    obs, rewards, dones, infos = self.venv.step_wait()
                                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 137, in step_wait
    results = [remote.recv() for remote in self.remotes]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 137, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
               ^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\multiprocessing\connection.py", line 337, in _recv_bytes
    raise EOFError
EOFError
2025-08-15 22:30:38 | WARNING | MainProcess | root | [INTERRUPT] KeyboardInterrupt — saving.
2025-08-15 23:45:43 | WARNING | MainProcess | root | [INTERRUPT] KeyboardInterrupt — saving.
2025-08-16 00:32:41 | WARNING | MainProcess | root | [INTERRUPT] KeyboardInterrupt — saving.
2025-08-16 00:32:45 | WARNING | MainProcess | root | [INTERRUPT] KeyboardInterrupt — saving.
2025-08-16 02:15:51 | ERROR | MainProcess | root | [ERROR] during learn: 
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\multiprocessing\connection.py", line 328, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bot\Train_RL.py", line 241, in train_one_file
    model.learn(total_timesteps=int(args.total_steps), callback=cb, progress_bar=args.progress)
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\ppo\ppo.py", line 311, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 324, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 218, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py", line 222, in step
    return self.step_wait()
           ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\vec_env\vec_normalize.py", line 181, in step_wait
    obs, rewards, dones, infos = self.venv.step_wait()
                                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 137, in step_wait
    results = [remote.recv() for remote in self.remotes]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 137, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
               ^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\bot-trade\Lib\multiprocessing\connection.py", line 337, in _recv_bytes
    raise EOFError
EOFError
2025-08-25 19:33:01 | WARNING | MainProcess | root | [INTERRUPT] KeyboardInterrupt — saving.
2025-08-25 21:07:55 | WARNING | MainProcess | root | [INTERRUPT] KeyboardInterrupt — saving.
2025-08-26 11:51:15 | WARNING | MainProcess | root | [INTERRUPT] KeyboardInterrupt — saving.
